#ifndef _TOKENTYPE_H
#define _TOKENTYPE_H

enum TokenType
{
    SELECT, CREATE, TABLE, INDEX, PRIMARY, KEY,
    INSERT, UPDATE, SET, WHERE, EQUAL, FROM, WILDCARD,
    COMMA, SEMI_COLUMN, ORDER, BY, ASC, DESC, ON,
    OPEN_PARENTHESES, CLOSE_PARENTHESES, QUOTES,
    STRING, INT, DOUBLE, TRUE, FALSE, END_OF_FILE, QUIT
};

#endif
